/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package AddressEJB

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'AddressEJB.greeting' plugin.
 */
public class AddressEJBPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("AddressEJB.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
